// components/About.vue
<template>
  <div class="px-10 md:px-5 h-screen md:h-auto md:py-10 py-16 w-full">
    <div v-motion-slide-visible-top class="w-full">
      <div id="about" class="section w-full flex items-center gap-4">
        <span class="text-green-500 font-semibold text-lg">01.</span>
        <span class="font-semibold text-white text-xl truncate">About me</span>
        <span class="w-1/3 bg-gray-700 h-[1px]"></span>
      </div>
      <div
        class="space-y-12 text-lg max-w-3xl font-medium text-gray-400 leading-9 my-6"
      >
        <p class="mb-3">
          Hello again! My name is Edson Ntwali and I am curiosity-driven full
          stack developer based in <a class="tagline">Rwanda</a>. <br />i enjoy
          developing things that will be used by others. My interest in software
          development started back in 2018 when I decided to join software
          development colledge. Then after i joined
          <a class="tagline">The Gym</a> trainings and gave me the right skills
          to grow my career.
        </p>
        <span
          >I've been building staff for the <a href="#" class="tagline">Web</a>
          &
          <a href="#" class="tagline">Mobile</a> for
          <a href="#" class="tagline">4+</a> years and i have worked with
          various clients and contributted to some
          <a href="#" class="tagline">open source</a> projects.
        </span>
      </div>
      <div class="mt-10">
        <h4 class="font-semibold text-white text-xl truncate">Personal Info</h4>
        <div class="grid md:grid-cols-1 max-w-xl my-6 grid-cols-2 gap-4">
          <div
            class="flex items-center gap-3"
            v-for="info in [
              { key: 'First Name', value: 'Ntwali' },
              { key: 'Last Name', value: 'Edson' },
              { key: 'Age', value: '22' },
              { key: 'Phone', value: '(+250) 788 209 629' },
              { key: 'Email', value: 'ntwaliedson9@gmai.com' },
            ]"
          >
            <span class="text-base font-semibold text-white"
              >{{ info.key }}:</span
            >
            <span class="text-gray-400 text-base font-medium">{{
              info.value
            }}</span>
          </div>
        </div>
      </div>
      <div class="py-12">
        <a
          class="flex items-center font-medium gap-4 text-white"
          aria-label="See More About Me"
          target="_blank"
          href="/resume.pdf"
          ><span>Download my resume.</span
          ><svg
            width="24"
            height="24"
            xmlns="http://www.w3.org/2000/svg"
            fill-rule="evenodd"
            clip-rule="evenodd"
            class="fill-current bounce-svg"
          >
            <path
              d="M21.883 12l-7.527 6.235.644.765 9-7.521-9-7.479-.645.764 7.529 6.236h-21.884v1h21.883z"
            ></path></svg
        ></a>
      </div>
    </div>
  </div>
</template>

// src/components/About.svelte
<div
  class="grid grid-cols-5 md:grid-cols-1 max-w-3xl py-16 mx-auto px-3 gap-10"
>
  <div class="col-span-2 relative">
    <div class="w-fit hidden- md:block">
      <div class="relative cursor-pointer group">
        <a href="#" target="_blank"
          ><img
            alt="Ntwali edson - Software deleveloper."
            src="/images/profile.jpg"
            width="220"
            height="220"
            class="rounded-[3px] z-50 transition-all delay-100 grayscale group-hover:grayscale-0"
          /></a
        >
        <div
          class="block w-full [3px] h-full transition-all delay-100 absolute group-hover:top-3 group-hover:left-3 -z-20 dark:border-slate-700 border-2 rounded-sm top-6 left-6"
        />
      </div>
    </div>
  </div>
  <div class="col-span-3 w-full">
    <div class="w-full">
      <div id="about" class="section w-full text-sm flex items-center gap-4">
        <span class="text-indigo-500 font-semibold text-base">01.</span><span
          class="font-semibold text-base text-indigo-500 truncate"
          >About me</span
        ><span class="w-1/3 bg-gray-100 dark:bg-slate-800 h-[1px]" />
      </div>
      <div
        class="space-y-3 text-[14px] max-w-3xl font-medium dark:text-slate-400 text-slate-500 leading-10 my-6"
      >
        <p class="mt-3">
          Hello again! My name is Edson Ntwali and I am curiosity-driven full
          stack developer based in <a class="tagline">Rwanda</a>.I enjoy
          developing things that will be used by others.
        </p>
      </div>
      <div class="mt-5">
        <div class="grid max-w-xl sm:grid-cols-1 my-6 grid-cols-2 gap-6">
          <div class="flex items-center gap-3">
            <span
              class="text-[14px] font-semibold text-slate-700 dark:text-slate-200"
              >First Name:</span
            ><span class="text-slate-400 text-[14px] font-medium">Ntwali</span>
          </div>
          <div class="flex items-center gap-3">
            <span
              class="text-[14px] font-semibold text-slate-700 dark:text-slate-200"
              >Last Name:</span
            ><span class="text-slate-400 text-[14px] font-medium">Edson</span>
          </div>
          <div class="flex items-center gap-3">
            <span
              class="text-[14px] font-semibold text-slate-700 dark:text-slate-200"
              >Phone:</span
            ><a
              href="tell:+250788209629"
              class="text-slate-400 text-[14px] font-medium"
              >(+250) 788 209 629</a
            >
          </div>
          <div class="flex items-center gap-3">
            <span
              class="text-[14px] font-semibold text-slate-700 dark:text-slate-200"
              >Email:</span
            ><a
              href="mailto:ntwaliedson9@gmai.com"
              class="text-slate-400 hover:underline text-[14px] font-medium"
              >ntwaliedson9@gmai.com</a
            >
          </div>
          <!--]-->
        </div>
      </div>
    </div>
  </div>
</div>
